language: node_js
node_js:
    - 10

services:
    - docker
cache:
    directories:
        - "$HOME/.npm"
        - "node_modules"

jobs:
    include:
        - stage: build docker image
          if: branch = master
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker build -t phoenix-scouter .
            - docker images
            - docker tag phoenix-scouter $DOCKER_USERNAME/phoenix-scouter
            - docker push $DOCKER_USERNAME/phoenix-scouter
