language: node_js
node_js:
    - 10

services:
    - docker
cache:
    directories:
        - "$HOME/.npm"
        - "node_modules"

deploy:
    provider: script
    script: bash ./docker_push.sh
    on:
        branch: master
